server: 
  port: 80
  
spring: 
   thymeleaf:
     prefix: classpath:/templates/  #prefix：指定模板所在的目录
     check-template-location: true  #check-tempate-location: 检查模板路径是否存在
     cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
     suffix:  .html
     #encoding: UTF-8
     #content-type: text/html
     mode: HTML5
 
   datasource: 
      url: jdbc:mysql://127.0.0.1/C71-S3-tljl-hotelmanagementsystem?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com:
      ljl: debug
      
 
#log日志等级： debug(所有的调试信息均要被调试出来) error warn info